- name: Running Kubernetes Cluster
  hosts: localhost
  become: yes
  tasks:
    - name: Clone the Healthcare Project Repository
      git:
        repo: "https://github.com/Balunideepak/healthcare-project.git"
        dest: "/tmp/healthcare-project"
        clone: yes
        update: yes
        force: yes
- name: Install kubectl
  become: yes
  apt:
    name: kubectl
    state: present
  when: ansible_os_family == 'Debian'

- name: Install kubectl (RHEL)
  become: yes
  yum:
    name: kubectl
    state: present
  when: ansible_os_family == 'RedHat'
    - name: Apply Kubernetes manifests
      command: kubectl apply -f /tmp/healthcare-project/deployment.yml
      register: k8s_output

    - name: Display kubectl apply output
      debug:
        var: k8s_output.stdout_lines
